// src/services/mockData.js
export const mockCurrencies = [
  {
    id: "1",
    name: "US Dollar",
    code: "USD",
    symbol: "$",
    buyRate: 1.0,
    sellRate: 1.0,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Euro",
    code: "EUR",
    symbol: "€",
    buyRate: 1.08,
    sellRate: 1.1,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "British Pound",
    code: "GBP",
    symbol: "£",
    buyRate: 1.25,
    sellRate: 1.27,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Ethiopian Birr",
    code: "ETB",
    symbol: "Br",
    buyRate: 0.018,
    sellRate: 0.019,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "UAE Dirham",
    code: "AED",
    symbol: "د.إ",
    buyRate: 0.27,
    sellRate: 0.28,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Saudi Riyal",
    code: "SAR",
    symbol: "﷼",
    buyRate: 0.27,
    sellRate: 0.27,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
    buyRate: 0.0067,
    sellRate: 0.0069,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Canadian Dollar",
    code: "CAD",
    symbol: "C$",
    buyRate: 0.73,
    sellRate: 0.74,
    status: "active",
    createdAt: new Date().toISOString(),
  },
];

export const mockCustomers = [
  {
    id: "1",
    fullName: "John Doe",
    phone: "+1234567890",
    email: "john@example.com",
    country: "USA",
    address: "123 Main St, New York",
    registrationDate: new Date().toISOString(),
  },
  {
    id: "2",
    fullName: "Jane Smith",
    phone: "+1987654321",
    email: "jane@example.com",
    country: "UK",
    address: "45 Oxford St, London",
    registrationDate: new Date().toISOString(),
  },
  {
    id: "3",
    fullName: "Mohamed Ali",
    phone: "+971501234567",
    email: "mohamed@example.com",
    country: "UAE",
    address: "Dubai Marina",
    registrationDate: new Date().toISOString(),
  },
  {
    id: "4",
    fullName: "Sarah Johnson",
    phone: "+16175551234",
    email: "sarah@example.com",
    country: "Canada",
    address: "Toronto, ON",
    registrationDate: new Date().toISOString(),
  },
];

export const mockTransactions = [
  {
    id: "TRX001",
    customerId: "1",
    customerName: "John Doe",
    fromCurrency: "USD",
    toCurrency: "EUR",
    amount: 1000,
    exchangeRate: 0.92,
    convertedAmount: 920,
    fee: 5,
    totalAmount: 925,
    status: "Completed",
    date: new Date().toISOString(),
  },
  {
    id: "TRX002",
    customerId: "2",
    customerName: "Jane Smith",
    fromCurrency: "GBP",
    toCurrency: "USD",
    amount: 500,
    exchangeRate: 1.27,
    convertedAmount: 635,
    fee: 3,
    totalAmount: 638,
    status: "Completed",
    date: new Date().toISOString(),
  },
  {
    id: "TRX003",
    customerId: "3",
    customerName: "Mohamed Ali",
    fromCurrency: "USD",
    toCurrency: "AED",
    amount: 2000,
    exchangeRate: 3.67,
    convertedAmount: 7340,
    fee: 10,
    totalAmount: 7350,
    status: "Pending",
    date: new Date().toISOString(),
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "transaction",
    title: "New Transaction",
    message: "Transaction TRX001 completed successfully",
    isRead: false,
    date: new Date().toISOString(),
  },
  {
    id: "2",
    type: "rate_update",
    title: "Rate Updated",
    message: "EUR/USD rate has been updated",
    isRead: false,
    date: new Date().toISOString(),
  },
  {
    id: "3",
    type: "customer",
    title: "New Customer",
    message: "John Doe registered as new customer",
    isRead: true,
    date: new Date().toISOString(),
  },
  {
    id: "4",
    type: "system",
    title: "System Alert",
    message: "System maintenance scheduled for tomorrow",
    isRead: false,
    date: new Date().toISOString(),
  },
];

export const mockUser = {
  id: "1",
  fullName: "Admin User",
  email: "admin@example.com",
  phone: "+1234567890",
  profileImage: null,
  role: "admin",
};
